### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by ancestrychanged** [SolovovChann/demotivator#30]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
  File "__main__.py", line 46, in create_demotivator
    demotivator = demotivate(
                  ^^^^^^^^^^^
  File "__init__.py", line 67, in demotivate
    pil_font = _load_font(font, int(unit * 8))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "__init__.py", line 97, in _load_font
    return ImageFont.truetype(font, size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\PIL\ImageFont.py", line 797, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "\PIL\ImageFont.py", line 794, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\PIL\ImageFont.py", line 226, in __init__
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource

**Comment by ancestrychanged** [comment]
replaced return ImageFont.truetype(font, size) with return ImageFont.truetype("times.ttf", size)
